name: Push to AUR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  aur:
    uses: pawprnt/.github/.github/workflows/aur-publish.yml@main
    with:
      pkgname: forager
    secrets: inherit
