name: Build Flatpak
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/kde:master
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Build
        id: flatpak
        uses: andyholmes/flatter@main
        with:
          files: packaging/flatpak/io.github.pawprnt.forager.yml
          upload-bundles: true

      - name: Clone flatpak-repo
        run: |
          git clone https://x-access-token:${{ secrets.FLATPAK_REPO_TOKEN }}@github.com/pawprnt/flatpak-repo.git /tmp/flatpak-repo

      - name: Update repo
        run: |
          mkdir -p /tmp/flatpak-repo/forager
          cp -r ${{ steps.flatpak.outputs.repository }} /tmp/flatpak-repo/forager/repo
          flatpak build-update-repo --generate-static-delta --prune /tmp/flatpak-repo/forager/repo

      - name: Push
        run: |
          cd /tmp/flatpak-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update forager" || exit 0
          git push
