name: Publish to Nix Registry

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  nix-publish:
    uses: pawprnt/.github/.github/workflows/nix-deploy.yml@main
    with:
      pkgname: forager
      nixpkgs-repo: pawprnt/nixpkgs
    secrets:
      NIX_GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
